name: Github Work
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger B repo
        if: github.ref == 'refs/heads/master'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.SSH_KEY }}" \
            https://api.github.com/repos/Huzhiwen1208/TestCI-B/dispatches \
            -d '{"event_type": "trigger-from-A"}'