name: Github Work
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        env:
          GH_TOKEN: ${{ secrets.SSH_KEY }}
          REPO: Huzhiwen1208/TestCI-B
          EVENT_TYPE: "trigger-from-A"
        run: |
          gh api --method POST \
            /repos/${REPO}/dispatches \
            -f "event_type=${EVENT_TYPE}"